### ISSUE TITLE
veritabanı

### ISSUE THREAD

**Issue by ByPikod** [AlparslanTR/YemekSitemFirst#2]
Hocam projenin veri tabanını eklemeyi unutmuşsunuz sanırım. Projenin veritabanını ekleyebilirseniz çok hoş olur.

**Comment by alparslanakbas** [comment]
çok eski seneler önce yaptığım bir tasarımdı. Githubdaki hiçbir projemde
sql tabanlar yüklü değil sadece göstermelik.

Yahya Batulu ***@***.***>, 5 Haz 2022 Paz, 11:30 tarihinde
şunu yazdı:

**Comment by ByPikod** [comment]
Aklıma geldi benim de böyle şeyler başıma geliyor eski projeleri yüklerken hocam. Lise düzeyinde bunun gibi bir kodu öğretmene açıklamamız gerekiyor bende hazır bulabilirsem diye bakındım da çoğu proje veritabanı hariç yüklenmiş.

**Comment by alparslanakbas** [comment]
Bence hocana daha iyisini bulabilirsin onda boostrap kütüphanesi yok yani
normal acemi bir kişinin yapabileceği düzeyde ki o zaman bende hiç birşey
bilmiyordum. Boostrapli bulabilirsin belki tasarımları daha hoş.

6 Haz 2022 Pzt 17:37 tarihinde Yahya Batulu ***@***.***> şunu
yazdı:

**Comment by ByPikod** [comment]
Ben açıklayacağım projeyi kendim kodladım. Bunu arkadaşlarım için teslim edecektim o yüzden kod düzgün mü değil mi pek ilgilenmedim :)
